## Load data

In [25]:
from pymongo import MongoClient
# 네트워크 연결 규칙 : protocol://ip:port/path 
client = MongoClient('mongodb://192.168.0.50:27017/')

db_name = client["DB_SGMN"]
col_src_name = db_name["COL_KOSIS_BUSINESS_CYCLE_SURVEY_FORECAST"]

In [26]:
data_cursor = col_src_name.find({
    "PRD_DE": {
        "$gte": "201501"  # 2015년 1월 이상
        },
    "C1_NM" : "서비스업"  # 추가 조건
})
data_list = list(data_cursor)
print(len(data_list))
data_list[:5]

720

[{'_id': ObjectId('67593413651b18fb01b84f4f'),
  'TBL_NM': '기업경기조사(전망)',
  'PRD_DE': '201501',
  'TBL_ID': 'DT_512Y014',
  'ITM_NM': '기업경기조사(전망)',
  'ITM_NM_ENG': 'National Future Tendency',
  'ITM_ID': '13103134488999',
  'ORG_ID': '301',
  'C1_OBJ_NM': '업종코드별',
  'C1_OBJ_NM_ENG': 'Code of Business Type',
  'C2_OBJ_NM': 'BSI코드별',
  'C2_OBJ_NM_ENG': 'BSI Code',
  'DT': '69',
  'PRD_SE': 'M',
  'C2': '13102134488BSI_CD.BA',
  'C1': '13102134488BUSINESS_TYPE_CD.Y9950',
  'C1_NM': '서비스업',
  'C2_NM': '업황전망BSI 1)',
  'C1_NM_ENG': 'Services',
  'C2_NM_ENG': 'Business Condition BSI',
  'LST_CHN_DE': '2024-12-11',
  'CREATED_AT': datetime.datetime(2024, 12, 11, 6, 41, 22, 147000)},
 {'_id': ObjectId('67593413651b18fb01b84f50'),
  'TBL_NM': '기업경기조사(전망)',
  'PRD_DE': '201502',
  'TBL_ID': 'DT_512Y014',
  'ITM_NM': '기업경기조사(전망)',
  'ITM_NM_ENG': 'National Future Tendency',
  'ITM_ID': '13103134488999',
  'ORG_ID': '301',
  'C1_OBJ_NM': '업종코드별',
  'C1_OBJ_NM_ENG': 'Code of Business Type',
  'C2_OBJ_NM': 'BSI코드별',
  'C2_OBJ_NM_ENG': 'BSI Code',
  'DT': '71',
  'PRD_SE': 'M',
  'C2': '13102134488BSI_CD.BA',
  'C1': '13102134488BUSINESS_TYPE_CD.Y9950',
  'C1_NM': '서비스업',
  'C2_NM': '업황전망BSI 1)',
  'C1_NM_ENG': 'Services',
  'C2_NM_ENG': 'Business Condition BSI',
  'LST_CHN_DE': '2024-12-11',
  'CREATED_AT': datetime.datetime(2024, 12, 11, 6, 41, 22, 147000)},
 {'_id': ObjectId('67593413651b18fb01b84f51'),
  'TBL_NM': '기업경기조사(전망)',
  'PRD_DE': '201503',
  'TBL_ID': 'DT_512Y014',
  'ITM_NM': '기업경기조사(전망)',
  'ITM_NM_ENG': 'National Future Tendency',
  'ITM_ID': '13103134488999',
  'ORG_ID': '301',
  'C1_OBJ_NM': '업종코드별',
  'C1_OBJ_NM_ENG': 'Code of Business Type',
  'C2_OBJ_NM': 'BSI코드별',
  'C2_OBJ_NM_ENG': 'BSI Code',
  'DT': '76',
  'PRD_SE': 'M',
  'C2': '13102134488BSI_CD.BA',
  'C1': '13102134488BUSINESS_TYPE_CD.Y9950',
  'C1_NM': '서비스업',
  'C2_NM': '업황전망BSI 1)',
  'C1_NM_ENG': 'Services',
  'C2_NM_ENG': 'Business Condition BSI',
  'LST_CHN_DE': '2024-12-11',
  'CREATED_AT': datetime.datetime(2024, 12, 11, 6, 41, 22, 147000)},
 {'_id': ObjectId('67593413651b18fb01b84f52'),
  'TBL_NM': '기업경기조사(전망)',
  'PRD_DE': '201504',
  'TBL_ID': 'DT_512Y014',
  'ITM_NM': '기업경기조사(전망)',
  'ITM_NM_ENG': 'National Future Tendency',
  'ITM_ID': '13103134488999',
  'ORG_ID': '301',
  'C1_OBJ_NM': '업종코드별',
  'C1_OBJ_NM_ENG': 'Code of Business Type',
  'C2_OBJ_NM': 'BSI코드별',
  'C2_OBJ_NM_ENG': 'BSI Code',
  'DT': '75',
  'PRD_SE': 'M',
  'C2': '13102134488BSI_CD.BA',
  'C1': '13102134488BUSINESS_TYPE_CD.Y9950',
  'C1_NM': '서비스업',
  'C2_NM': '업황전망BSI 1)',
  'C1_NM_ENG': 'Services',
  'C2_NM_ENG': 'Business Condition BSI',
  'LST_CHN_DE': '2024-12-11',
  'CREATED_AT': datetime.datetime(2024, 12, 11, 6, 41, 22, 147000)},
 {'_id': ObjectId('67593413651b18fb01b84f53'),
  'TBL_NM': '기업경기조사(전망)',
  'PRD_DE': '201505',
  'TBL_ID': 'DT_512Y014',
  'ITM_NM': '기업경기조사(전망)',
  'ITM_NM_ENG': 'National Future Tendency',
  'ITM_ID': '13103134488999',
  'ORG_ID': '301',
  'C1_OBJ_NM': '업종코드별',
  'C1_OBJ_NM_ENG': 'Code of Business Type',
  'C2_OBJ_NM': 'BSI코드별',
  'C2_OBJ_NM_ENG': 'BSI Code',
  'DT': '79',
  'PRD_SE': 'M',
  'C2': '13102134488BSI_CD.BA',
  'C1': '13102134488BUSINESS_TYPE_CD.Y9950',
  'C1_NM': '서비스업',
  'C2_NM': '업황전망BSI 1)',
  'C1_NM_ENG': 'Services',
  'C2_NM_ENG': 'Business Condition BSI',
  'LST_CHN_DE': '2024-12-11',
  'CREATED_AT': datetime.datetime(2024, 12, 11, 6, 41, 22, 147000)}]

In [27]:
data_cursor = col_src_name.find({
    "$and": [
        {
            "PRD_DE": {
                "$gte": "201501"  # 2015년 1월 이상
            }
        },
        {
            "C1_NM" : {
               "$eq" : "서비스업"  # 추가 조건
            }
        },
        {
            "C2_NM_ENG": {
                "$regex": "growth",  
                "$options": "i"         
            }
        }
    ]
})
data_list = list(data_cursor)
print(len(data_list))
data_list[:5]

120

[{'_id': ObjectId('67593413651b18fb01b84fd3'),
  'TBL_NM': '기업경기조사(전망)',
  'PRD_DE': '201501',
  'TBL_ID': 'DT_512Y014',
  'ITM_NM': '기업경기조사(전망)',
  'ITM_NM_ENG': 'National Future Tendency',
  'ITM_ID': '13103134488999',
  'ORG_ID': '301',
  'C1_OBJ_NM': '업종코드별',
  'C1_OBJ_NM_ENG': 'Code of Business Type',
  'C2_OBJ_NM': 'BSI코드별',
  'C2_OBJ_NM_ENG': 'BSI Code',
  'DT': '80',
  'PRD_SE': 'M',
  'C2': '13102134488BSI_CD.BB',
  'C1': '13102134488BUSINESS_TYPE_CD.Y9950',
  'C1_NM': '서비스업',
  'C2_NM': '매출전망BSI 2)',
  'C1_NM_ENG': 'Services',
  'C2_NM_ENG': 'Sales Growth BSI',
  'LST_CHN_DE': '2024-12-11',
  'CREATED_AT': datetime.datetime(2024, 12, 11, 6, 41, 22, 147000)},
 {'_id': ObjectId('67593413651b18fb01b84fd4'),
  'TBL_NM': '기업경기조사(전망)',
  'PRD_DE': '201502',
  'TBL_ID': 'DT_512Y014',
  'ITM_NM': '기업경기조사(전망)',
  'ITM_NM_ENG': 'National Future Tendency',
  'ITM_ID': '13103134488999',
  'ORG_ID': '301',
  'C1_OBJ_NM': '업종코드별',
  'C1_OBJ_NM_ENG': 'Code of Business Type',
  'C2_OBJ_NM': 'BSI코드별',
  'C2_OBJ_NM_ENG': 'BSI Code',
  'DT': '84',
  'PRD_SE': 'M',
  'C2': '13102134488BSI_CD.BB',
  'C1': '13102134488BUSINESS_TYPE_CD.Y9950',
  'C1_NM': '서비스업',
  'C2_NM': '매출전망BSI 2)',
  'C1_NM_ENG': 'Services',
  'C2_NM_ENG': 'Sales Growth BSI',
  'LST_CHN_DE': '2024-12-11',
  'CREATED_AT': datetime.datetime(2024, 12, 11, 6, 41, 22, 147000)},
 {'_id': ObjectId('67593413651b18fb01b84fd5'),
  'TBL_NM': '기업경기조사(전망)',
  'PRD_DE': '201503',
  'TBL_ID': 'DT_512Y014',
  'ITM_NM': '기업경기조사(전망)',
  'ITM_NM_ENG': 'National Future Tendency',
  'ITM_ID': '13103134488999',
  'ORG_ID': '301',
  'C1_OBJ_NM': '업종코드별',
  'C1_OBJ_NM_ENG': 'Code of Business Type',
  'C2_OBJ_NM': 'BSI코드별',
  'C2_OBJ_NM_ENG': 'BSI Code',
  'DT': '87',
  'PRD_SE': 'M',
  'C2': '13102134488BSI_CD.BB',
  'C1': '13102134488BUSINESS_TYPE_CD.Y9950',
  'C1_NM': '서비스업',
  'C2_NM': '매출전망BSI 2)',
  'C1_NM_ENG': 'Services',
  'C2_NM_ENG': 'Sales Growth BSI',
  'LST_CHN_DE': '2024-12-11',
  'CREATED_AT': datetime.datetime(2024, 12, 11, 6, 41, 22, 147000)},
 {'_id': ObjectId('67593413651b18fb01b84fd6'),
  'TBL_NM': '기업경기조사(전망)',
  'PRD_DE': '201504',
  'TBL_ID': 'DT_512Y014',
  'ITM_NM': '기업경기조사(전망)',
  'ITM_NM_ENG': 'National Future Tendency',
  'ITM_ID': '13103134488999',
  'ORG_ID': '301',
  'C1_OBJ_NM': '업종코드별',
  'C1_OBJ_NM_ENG': 'Code of Business Type',
  'C2_OBJ_NM': 'BSI코드별',
  'C2_OBJ_NM_ENG': 'BSI Code',
  'DT': '86',
  'PRD_SE': 'M',
  'C2': '13102134488BSI_CD.BB',
  'C1': '13102134488BUSINESS_TYPE_CD.Y9950',
  'C1_NM': '서비스업',
  'C2_NM': '매출전망BSI 2)',
  'C1_NM_ENG': 'Services',
  'C2_NM_ENG': 'Sales Growth BSI',
  'LST_CHN_DE': '2024-12-11',
  'CREATED_AT': datetime.datetime(2024, 12, 11, 6, 41, 22, 147000)},
 {'_id': ObjectId('67593413651b18fb01b84fd7'),
  'TBL_NM': '기업경기조사(전망)',
  'PRD_DE': '201505',
  'TBL_ID': 'DT_512Y014',
  'ITM_NM': '기업경기조사(전망)',
  'ITM_NM_ENG': 'National Future Tendency',
  'ITM_ID': '13103134488999',
  'ORG_ID': '301',
  'C1_OBJ_NM': '업종코드별',
  'C1_OBJ_NM_ENG': 'Code of Business Type',
  'C2_OBJ_NM': 'BSI코드별',
  'C2_OBJ_NM_ENG': 'BSI Code',
  'DT': '88',
  'PRD_SE': 'M',
  'C2': '13102134488BSI_CD.BB',
  'C1': '13102134488BUSINESS_TYPE_CD.Y9950',
  'C1_NM': '서비스업',
  'C2_NM': '매출전망BSI 2)',
  'C1_NM_ENG': 'Services',
  'C2_NM_ENG': 'Sales Growth BSI',
  'LST_CHN_DE': '2024-12-11',
  'CREATED_AT': datetime.datetime(2024, 12, 11, 6, 41, 22, 147000)}]

## data with pandas

In [28]:
import pandas as pd

df_data = pd.DataFrame(data_list)

In [29]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   _id            120 non-null    object
 1   TBL_NM         120 non-null    object
 2   PRD_DE         120 non-null    object
 3   TBL_ID         120 non-null    object
 4   ITM_NM         120 non-null    object
 5   ITM_NM_ENG     120 non-null    object
 6   ITM_ID         120 non-null    object
 7   ORG_ID         120 non-null    object
 8   C1_OBJ_NM      120 non-null    object
 9   C1_OBJ_NM_ENG  120 non-null    object
 10  C2_OBJ_NM      120 non-null    object
 11  C2_OBJ_NM_ENG  120 non-null    object
 12  DT             120 non-null    object
 13  PRD_SE         120 non-null    object
 14  C2             120 non-null    object
 15  C1             120 non-null    object
 16  C1_NM          120 non-null    object
 17  C2_NM          120 non-null    object
 18  C1_NM_ENG      120 non-null    object
 19  C2_NM_ENG      120 non-null    object
 20  LST_CHN_DE     120 non-null    object
 21  CREATED_AT     120 non-null    datetime64[ns]
dtypes: datetime64[ns](1), object(21)
memory usage: 20.8+ KB

In [30]:
df_data.describe(include="all")

,_id,TBL_NM,PRD_DE,TBL_ID,ITM_NM,ITM_NM_ENG,ITM_ID,ORG_ID,C1_OBJ_NM,C1_OBJ_NM_ENG,...,DT,PRD_SE,C2,C1,C1_NM,C2_NM,C1_NM_ENG,C2_NM_ENG,LST_CHN_DE,CREATED_AT
count,120,120,120,120,120,120,120,120,120,120,...,120,120,120,120,120,120,120,120,120,120
unique,120,1,120,1,1,1,1,1,1,1,...,32,1,1,1,1,1,1,1,1,NaN
top,67593413651b18fb01b8503b,기업경기조사(전망),202309,DT_512Y014,기업경기조사(전망),National Future Tendency,13103134488999,301,업종코드별,Code of Business Type,...,84,M,13102134488BSI_CD.BB,13102134488BUSINESS_TYPE_CD.Y9950,서비스업,매출전망BSI 2),Services,Sales Growth BSI,2024-12-11,NaN
freq,1,120,1,120,120,120,120,120,120,120,...,11,120,120,120,120,120,120,120,120,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-11 06:41:22.147000064
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-11 06:41:22.147000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-11 06:41:22.147000064
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-11 06:41:22.147000064
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-11 06:41:22.147000064
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-11 06:41:22.147000

## Save data

In [31]:
from pymongo import MongoClient
# 네트워크 연결 규칙 : protocol://ip:port/path 
client = MongoClient('mongodb://192.168.0.91:27017/')

db_name = client["DB_TEST"]
col_target_name = db_name["COL_KOSIS_BUSINESS_CYCLE_SURVEY_FORECAST_T"]

In [33]:
df_data_without_id = df_data.drop(labels='_id', axis=1)
data_insert = df_data_without_id.to_dict(orient="records")
col_target_name.insert_many(data_insert)

InsertManyResult([ObjectId('675b9e64c2d98c7708eef77b'), ObjectId('675b9e64c2d98c7708eef77c'), ObjectId('675b9e64c2d98c7708eef77d'), ObjectId('675b9e64c2d98c7708eef77e'), ObjectId('675b9e64c2d98c7708eef77f'), ObjectId('675b9e64c2d98c7708eef780'), ObjectId('675b9e64c2d98c7708eef781'), ObjectId('675b9e64c2d98c7708eef782'), ObjectId('675b9e64c2d98c7708eef783'), ObjectId('675b9e64c2d98c7708eef784'), ObjectId('675b9e64c2d98c7708eef785'), ObjectId('675b9e64c2d98c7708eef786'), ObjectId('675b9e64c2d98c7708eef787'), ObjectId('675b9e64c2d98c7708eef788'), ObjectId('675b9e64c2d98c7708eef789'), ObjectId('675b9e64c2d98c7708eef78a'), ObjectId('675b9e64c2d98c7708eef78b'), ObjectId('675b9e64c2d98c7708eef78c'), ObjectId('675b9e64c2d98c7708eef78d'), ObjectId('675b9e64c2d98c7708eef78e'), ObjectId('675b9e64c2d98c7708eef78f'), ObjectId('675b9e64c2d98c7708eef790'), ObjectId('675b9e64c2d98c7708eef791'), ObjectId('675b9e64c2d98c7708eef792'), ObjectId('675b9e64c2d98c7708eef793'), ObjectId('675b9e64c2d98c7708eef794'), ObjectId('675b9e64c2d98c7708eef795'), ObjectId('675b9e64c2d98c7708eef796'), ObjectId('675b9e64c2d98c7708eef797'), ObjectId('675b9e64c2d98c7708eef798'), ObjectId('675b9e64c2d98c7708eef799'), ObjectId('675b9e64c2d98c7708eef79a'), ObjectId('675b9e64c2d98c7708eef79b'), ObjectId('675b9e64c2d98c7708eef79c'), ObjectId('675b9e64c2d98c7708eef79d'), ObjectId('675b9e64c2d98c7708eef79e'), ObjectId('675b9e64c2d98c7708eef79f'), ObjectId('675b9e64c2d98c7708eef7a0'), ObjectId('675b9e64c2d98c7708eef7a1'), ObjectId('675b9e64c2d98c7708eef7a2'), ObjectId('675b9e64c2d98c7708eef7a3'), ObjectId('675b9e64c2d98c7708eef7a4'), ObjectId('675b9e64c2d98c7708eef7a5'), ObjectId('675b9e64c2d98c7708eef7a6'), ObjectId('675b9e64c2d98c7708eef7a7'), ObjectId('675b9e64c2d98c7708eef7a8'), ObjectId('675b9e64c2d98c7708eef7a9'), ObjectId('675b9e64c2d98c7708eef7aa'), ObjectId('675b9e64c2d98c7708eef7ab'), ObjectId('675b9e64c2d98c7708eef7ac'), ObjectId('675b9e64c2d98c7708eef7ad'), ObjectId('675b9e64c2d98c7708eef7ae'), ObjectId('675b9e64c2d98c7708eef7af'), ObjectId('675b9e64c2d98c7708eef7b0'), ObjectId('675b9e64c2d98c7708eef7b1'), ObjectId('675b9e64c2d98c7708eef7b2'), ObjectId('675b9e64c2d98c7708eef7b3'), ObjectId('675b9e64c2d98c7708eef7b4'), ObjectId('675b9e64c2d98c7708eef7b5'), ObjectId('675b9e64c2d98c7708eef7b6'), ObjectId('675b9e64c2d98c7708eef7b7'), ObjectId('675b9e64c2d98c7708eef7b8'), ObjectId('675b9e64c2d98c7708eef7b9'), ObjectId('675b9e64c2d98c7708eef7ba'), ObjectId('675b9e64c2d98c7708eef7bb'), ObjectId('675b9e64c2d98c7708eef7bc'), ObjectId('675b9e64c2d98c7708eef7bd'), ObjectId('675b9e64c2d98c7708eef7be'), ObjectId('675b9e64c2d98c7708eef7bf'), ObjectId('675b9e64c2d98c7708eef7c0'), ObjectId('675b9e64c2d98c7708eef7c1'), ObjectId('675b9e64c2d98c7708eef7c2'), ObjectId('675b9e64c2d98c7708eef7c3'), ObjectId('675b9e64c2d98c7708eef7c4'), ObjectId('675b9e64c2d98c7708eef7c5'), ObjectId('675b9e64c2d98c7708eef7c6'), ObjectId('675b9e64c2d98c7708eef7c7'), ObjectId('675b9e64c2d98c7708eef7c8'), ObjectId('675b9e64c2d98c7708eef7c9'), ObjectId('675b9e64c2d98c7708eef7ca'), ObjectId('675b9e64c2d98c7708eef7cb'), ObjectId('675b9e64c2d98c7708eef7cc'), ObjectId('675b9e64c2d98c7708eef7cd'), ObjectId('675b9e64c2d98c7708eef7ce'), ObjectId('675b9e64c2d98c7708eef7cf'), ObjectId('675b9e64c2d98c7708eef7d0'), ObjectId('675b9e64c2d98c7708eef7d1'), ObjectId('675b9e64c2d98c7708eef7d2'), ObjectId('675b9e64c2d98c7708eef7d3'), ObjectId('675b9e64c2d98c7708eef7d4'), ObjectId('675b9e64c2d98c7708eef7d5'), ObjectId('675b9e64c2d98c7708eef7d6'), ObjectId('675b9e64c2d98c7708eef7d7'), ObjectId('675b9e64c2d98c7708eef7d8'), ObjectId('675b9e64c2d98c7708eef7d9'), ObjectId('675b9e64c2d98c7708eef7da'), ObjectId('675b9e64c2d98c7708eef7db'), ObjectId('675b9e64c2d98c7708eef7dc'), ObjectId('675b9e64c2d98c7708eef7dd'), ObjectId('675b9e64c2d98c7708eef7de'), ObjectId('675b9e64c2d98c7708eef7df'), ObjectId('675b9e64c2d98c7708eef7e0'), ObjectId('675b9e64c2d98c7708eef7e1'), ObjectId('675b9e64c2d98c7708eef7e2'), ObjectId('675b9e64c2d98c7708eef7e3'), ObjectId('675b9e64c2d98c7708eef7e4'), ObjectId('675b9e64c2d98c7708eef7e5'), ObjectId('675b9e64c2d98c7708eef7e6'), ObjectId('675b9e64c2d98c7708eef7e7'), ObjectId('675b9e64c2d98c7708eef7e8'), ObjectId('675b9e64c2d98c7708eef7e9'), ObjectId('675b9e64c2d98c7708eef7ea'), ObjectId('675b9e64c2d98c7708eef7eb'), ObjectId('675b9e64c2d98c7708eef7ec'), ObjectId('675b9e64c2d98c7708eef7ed'), ObjectId('675b9e64c2d98c7708eef7ee'), ObjectId('675b9e64c2d98c7708eef7ef'), ObjectId('675b9e64c2d98c7708eef7f0'), ObjectId('675b9e64c2d98c7708eef7f1'), ObjectId('675b9e64c2d98c7708eef7f2')], acknowledged=True)

In [34]:
data_cursor_result = col_target_name.find()
data_lis_result = list(data_cursor_result)
print(len(data_lis_result))
data_lis_result[:5]

240

[{'_id': ObjectId('67593413651b18fb01b84fd3'),
  'TBL_NM': '기업경기조사(전망)',
  'PRD_DE': '201501',
  'TBL_ID': 'DT_512Y014',
  'ITM_NM': '기업경기조사(전망)',
  'ITM_NM_ENG': 'National Future Tendency',
  'ITM_ID': '13103134488999',
  'ORG_ID': '301',
  'C1_OBJ_NM': '업종코드별',
  'C1_OBJ_NM_ENG': 'Code of Business Type',
  'C2_OBJ_NM': 'BSI코드별',
  'C2_OBJ_NM_ENG': 'BSI Code',
  'DT': '80',
  'PRD_SE': 'M',
  'C2': '13102134488BSI_CD.BB',
  'C1': '13102134488BUSINESS_TYPE_CD.Y9950',
  'C1_NM': '서비스업',
  'C2_NM': '매출전망BSI 2)',
  'C1_NM_ENG': 'Services',
  'C2_NM_ENG': 'Sales Growth BSI',
  'LST_CHN_DE': '2024-12-11',
  'CREATED_AT': datetime.datetime(2024, 12, 11, 6, 41, 22, 147000)},
 {'_id': ObjectId('67593413651b18fb01b84fd4'),
  'TBL_NM': '기업경기조사(전망)',
  'PRD_DE': '201502',
  'TBL_ID': 'DT_512Y014',
  'ITM_NM': '기업경기조사(전망)',
  'ITM_NM_ENG': 'National Future Tendency',
  'ITM_ID': '13103134488999',
  'ORG_ID': '301',
  'C1_OBJ_NM': '업종코드별',
  'C1_OBJ_NM_ENG': 'Code of Business Type',
  'C2_OBJ_NM': 'BSI코드별',
  'C2_OBJ_NM_ENG': 'BSI Code',
  'DT': '84',
  'PRD_SE': 'M',
  'C2': '13102134488BSI_CD.BB',
  'C1': '13102134488BUSINESS_TYPE_CD.Y9950',
  'C1_NM': '서비스업',
  'C2_NM': '매출전망BSI 2)',
  'C1_NM_ENG': 'Services',
  'C2_NM_ENG': 'Sales Growth BSI',
  'LST_CHN_DE': '2024-12-11',
  'CREATED_AT': datetime.datetime(2024, 12, 11, 6, 41, 22, 147000)},
 {'_id': ObjectId('67593413651b18fb01b84fd5'),
  'TBL_NM': '기업경기조사(전망)',
  'PRD_DE': '201503',
  'TBL_ID': 'DT_512Y014',
  'ITM_NM': '기업경기조사(전망)',
  'ITM_NM_ENG': 'National Future Tendency',
  'ITM_ID': '13103134488999',
  'ORG_ID': '301',
  'C1_OBJ_NM': '업종코드별',
  'C1_OBJ_NM_ENG': 'Code of Business Type',
  'C2_OBJ_NM': 'BSI코드별',
  'C2_OBJ_NM_ENG': 'BSI Code',
  'DT': '87',
  'PRD_SE': 'M',
  'C2': '13102134488BSI_CD.BB',
  'C1': '13102134488BUSINESS_TYPE_CD.Y9950',
  'C1_NM': '서비스업',
  'C2_NM': '매출전망BSI 2)',
  'C1_NM_ENG': 'Services',
  'C2_NM_ENG': 'Sales Growth BSI',
  'LST_CHN_DE': '2024-12-11',
  'CREATED_AT': datetime.datetime(2024, 12, 11, 6, 41, 22, 147000)},
 {'_id': ObjectId('67593413651b18fb01b84fd6'),
  'TBL_NM': '기업경기조사(전망)',
  'PRD_DE': '201504',
  'TBL_ID': 'DT_512Y014',
  'ITM_NM': '기업경기조사(전망)',
  'ITM_NM_ENG': 'National Future Tendency',
  'ITM_ID': '13103134488999',
  'ORG_ID': '301',
  'C1_OBJ_NM': '업종코드별',
  'C1_OBJ_NM_ENG': 'Code of Business Type',
  'C2_OBJ_NM': 'BSI코드별',
  'C2_OBJ_NM_ENG': 'BSI Code',
  'DT': '86',
  'PRD_SE': 'M',
  'C2': '13102134488BSI_CD.BB',
  'C1': '13102134488BUSINESS_TYPE_CD.Y9950',
  'C1_NM': '서비스업',
  'C2_NM': '매출전망BSI 2)',
  'C1_NM_ENG': 'Services',
  'C2_NM_ENG': 'Sales Growth BSI',
  'LST_CHN_DE': '2024-12-11',
  'CREATED_AT': datetime.datetime(2024, 12, 11, 6, 41, 22, 147000)},
 {'_id': ObjectId('67593413651b18fb01b84fd7'),
  'TBL_NM': '기업경기조사(전망)',
  'PRD_DE': '201505',
  'TBL_ID': 'DT_512Y014',
  'ITM_NM': '기업경기조사(전망)',
  'ITM_NM_ENG': 'National Future Tendency',
  'ITM_ID': '13103134488999',
  'ORG_ID': '301',
  'C1_OBJ_NM': '업종코드별',
  'C1_OBJ_NM_ENG': 'Code of Business Type',
  'C2_OBJ_NM': 'BSI코드별',
  'C2_OBJ_NM_ENG': 'BSI Code',
  'DT': '88',
  'PRD_SE': 'M',
  'C2': '13102134488BSI_CD.BB',
  'C1': '13102134488BUSINESS_TYPE_CD.Y9950',
  'C1_NM': '서비스업',
  'C2_NM': '매출전망BSI 2)',
  'C1_NM_ENG': 'Services',
  'C2_NM_ENG': 'Sales Growth BSI',
  'LST_CHN_DE': '2024-12-11',
  'CREATED_AT': datetime.datetime(2024, 12, 11, 6, 41, 22, 147000)}]